version: '3'
services:
  mysql:
    image: mysql
    container_name: spccweb-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spcc
      - MYSQL_USER=spcc
      - MYSQL_PASSWORD=root
  app:
    image: ambientum/php:7.3-nginx
    container_name: spccweb-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    environment:
      - XDEBUG_ENABLED=true
      - APP_NAME='SPCC - Caloocan'
      - APP_URL=http://localhost:8000
    depends_on:
      - mysql
